// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4505.MecanumBot14.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.networktables.NetworkTable;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc4505.MecanumBot14.Robot;
import org.usfirst.frc4505.MecanumBot14.RobotMap;
/**
 *
 */
public class  MecanumDriveRobot extends Command {
    public MecanumDriveRobot() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        SmartDashboard.putNumber("Move_Trigger_Cont1", Robot.oi.getTrigger1());
        NetworkTable.getTable("table").putNumber("Cont1Mag", Robot.driveTrain.slowDown(Robot.oi.controllerUno.getMagnitude()));
        NetworkTable.getTable("table").putNumber("Cont1Dir", Robot.oi.controllerUno.getDirectionDegrees());
        NetworkTable.getTable("table").putNumber("Cont1..2X", Robot.oi.getSecondX());
        SmartDashboard.putNumber("Cont1Mag", NetworkTable.getTable("table").getNumber("Cont1Mag"));
        SmartDashboard.putNumber("Cont1Dir", NetworkTable.getTable("table").getNumber("Cont1Dir"));
        SmartDashboard.putNumber("Cont1..2X", NetworkTable.getTable("table").getNumber("Cont1..2X"));
        Robot.driveTrain.driveBot(Robot.oi.controllerUno.getMagnitude(), Robot.oi.controllerUno.getDirectionDegrees(), Robot.oi.getSecondX());
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
        Robot.driveTrain.driveBot(0.0, 0.0, 0.0);
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
