// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4505.FinalCompetitionBot14.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc4505.FinalCompetitionBot14.Robot;
/**
 *
 */
public class  DriveRobot extends Command {
    public DriveRobot() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        SmartDashboard.putNumber("Move_Trigger_Cont1", Robot.oi.getTrigger1());
        SmartDashboard.putNumber("Cont1Mag",Robot.drivetrain.slowDown(Robot.oi.xboxControllerOne.getMagnitude()));
        SmartDashboard.putNumber("Cont1Dir", Robot.oi.xboxControllerOne.getDirectionDegrees());
        SmartDashboard.putNumber("Cont1..2X", Robot.oi.getSecondX());
        Robot.drivetrain.driveBot(Robot.oi.xboxControllerOne.getMagnitude(), Robot.oi.xboxControllerOne.getDirectionDegrees(), Robot.oi.getSecondX());
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
        Robot.drivetrain.driveBot(0.0, 0.0, 0.0);
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
