// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4505.DriveTrainBuild14;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainFrontLeft;
    public static SpeedController drivetrainFrontRight;
    public static SpeedController drivetrainBackLeft;
    public static SpeedController drivetrainBackRight;
    public static RobotDrive drivetrainRobotDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainFrontLeft = new Victor(1, 1);
	LiveWindow.addActuator("Drivetrain", "FrontLeft", (Victor) drivetrainFrontLeft);
        
        drivetrainFrontRight = new Victor(1, 2);
	LiveWindow.addActuator("Drivetrain", "FrontRight", (Victor) drivetrainFrontRight);
        
        drivetrainBackLeft = new Victor(1, 3);
	LiveWindow.addActuator("Drivetrain", "BackLeft", (Victor) drivetrainBackLeft);
        
        drivetrainBackRight = new Victor(1, 4);
	LiveWindow.addActuator("Drivetrain", "BackRight", (Victor) drivetrainBackRight);
        
        drivetrainRobotDrive = new RobotDrive(drivetrainFrontLeft, drivetrainBackLeft,
              drivetrainFrontRight, drivetrainBackRight);
	
        drivetrainRobotDrive.setSafetyEnabled(true);
        drivetrainRobotDrive.setExpiration(0.1);
        drivetrainRobotDrive.setSensitivity(0.5);
        drivetrainRobotDrive.setMaxOutput(1.0);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
