// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4505.BoBBot14.subsystems;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc4505.BoBBot14.Robot;
import org.usfirst.frc4505.BoBBot14.RobotMap;
import org.usfirst.frc4505.BoBBot14.commands.*;
/**
 *
 */
public class Grabber extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController sucker = RobotMap.grabberSucker;
    DoubleSolenoid grabberSolenoid = RobotMap.grabberGrabberSolenoid;
    Compressor compressor = RobotMap.grabberCompressor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid shooterSolenoid = RobotMap.shooterSolenoid;
    
    public Grabber() {
        compressor.start();
    }
    
    public void useSucker() {
        if (Robot.oi.getTrigger2() > .8) {
            grabberSolenoid.set(DoubleSolenoid.Value.kReverse);//wrong button
            sucker.set(1.0);
        }
        if (Robot.oi.getXboxControllerTwo().getRawButton(5)) {//wrong button
            grabberSolenoid.set(DoubleSolenoid.Value.kForward);
            sucker.set(0.0);
        }
        
        if (Robot.oi.getXboxControllerTwo().getRawButton(2)) {
            while (Robot.oi.getXboxControllerTwo().getRawButton(2)) {
                sucker.set(-1.0);
                Robot.drivetrain.driveBot(Robot.oi.xboxControllerOne.getMagnitude(), Robot.oi.xboxControllerOne.getDirectionDegrees(), Robot.oi.getSecondX());
            }
            sucker.set(0.0);
        }
    }
    
    public void autoSuck(double time) {
        double startTime = Timer.getFPGATimestamp();
        while(Timer.getFPGATimestamp() - startTime < time){
            Robot.grabber.sucker.set(1.0);
        }
        Robot.grabber.sucker.set(0.0);
    }
    
    public void stopSuck() {
        Robot.grabber.sucker.set(0.0);
    }
    
    public void autoPutDown() {
        grabberSolenoid.set(DoubleSolenoid.Value.kReverse);
    }
    
    public void autoPutUp() {
        grabberSolenoid.set(DoubleSolenoid.Value.kForward);
    }
    
    public void pvcUp() {
        shooterSolenoid.set(DoubleSolenoid.Value.kForward);
    }
    
    public void pvcDown () {
        shooterSolenoid.set(DoubleSolenoid.Value.kReverse);
    }
    
    public void useShooter() {
        if (Robot.oi.getTrigger2()< -.8) {//wrong button
            sucker.set(0.0);
            shooterSolenoid.set(DoubleSolenoid.Value.kForward);
        }
        if (Robot.oi.getXboxControllerTwo().getRawButton(6)) {//wrong button
            shooterSolenoid.set(DoubleSolenoid.Value.kReverse);
        }
    }
    
    
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new ControlBall());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
